spring:
  main:
    show-banner: off
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useSSL=false
    username: root
    password: 12345
  mail:
    username: zhuoyueda@163.com
    host: smtp.163.com
    password: BTLXGEJAGRTOSRGK
    port: 465
    test-connection: on
    properties.mail.smtp.ssl.enable: true
    protocol: smtp

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379
  #    password: 123456
  #    jedis:
  #      pool:
  #        max-active: 8
  #        max-wait: -1
  #        max-idle: 500
  #        min-idle: 0
  #    lettuce:
  #      shutdown-timeout: 0


